sudo: required
services: 
  - docker
before_install:
  - docker build -t alexander-bautista/docker.react -f  Dockerfile.dev .
script:
  - docker run alexander-bautista/docker.react npm run test --  --coverage